version: '3.9'
services:
    nginx_server:
      image: nginx
      container_name: my_nginx
      volumes:
        - ./ng/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "80:8080"
    hw_server:
      build: ./hw
      container_name: hw
